# https://docs.docker.com/compose/compose-file/

services:
  fastapi_app:  # Name your service
    build: .  # Build the image from the current directory (.)
    command: ["uvicorn", "cs231n-spr-2025.main:app", "--host", "0.0.0.0", "--reload"]
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    volumes:
      - ./src:/app/src  # Mount your source code directory
